name: Dataset Unit Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  dataset-tests:
    uses: BuroHappoldEngineeringAdmin/CI_Toolkit/.github/workflows/ci-dataset-tests.yml@feat/ci-dataset-tests-inputs-and-hard-fail
    secrets:
      BHOM_APP_ID: ${{ secrets.BHOM_APP_ID }}
      BHOM_APP_PRIVATE_KEY: ${{ secrets.BHOM_APP_PRIVATE_KEY }}
