name: Dataset Compliance

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  dataset-compliance:
    uses: BuroHappoldEngineeringAdmin/CI_Toolkit/.github/workflows/ci-dataset-compliance.yml@pr61-test
    secrets:
      BHOM_APP_ID: ${{ secrets.BHOM_APP_ID }}
      BHOM_APP_PRIVATE_KEY: ${{ secrets.BHOM_APP_PRIVATE_KEY }}
