# Sandbox proxy -- calls CI_Toolkit on develop with test_all: true.

name: Versioning (release)

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  versioning:
    uses: BuroHappoldEngineeringAdmin/CI_Toolkit/.github/workflows/ci-versioning.yml@pr61-test
    secrets:
      BHOM_APP_ID: ${{ secrets.BHOM_APP_ID }}
      BHOM_APP_PRIVATE_KEY: ${{ secrets.BHOM_APP_PRIVATE_KEY }}
    with:
      test_all: true
      versioning_toolkit_repo: 'BuroHappoldEngineeringSandbox/Versioning_Toolkit'
